DTC_INCLUDE += $(srctree)/../onyx-modules/qcom/opensource/synx-kernel

ifeq ($(CONFIG_ARCH_SUN), y)
include $(srctree)/$(src)/config/sun.mk
endif

always-y	:= $(dtbo-y) $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb *.dtbo
